PROJ = simple_serial

TOOLCHAIN_DIR = ../../sdk/toolchain
LIB_DIR = ../../sdk/lib

SRC  = simpleserial.c
SRC += simpleserial-test.c


INC = -I../common


OBJ_DUMP = 1 # Uncomment if disassembly is needed

# Optimization level
OPTIMIZATION = -O0

include $(TOOLCHAIN_DIR)/makefile
