PROJ = uart_example

TOOLCHAIN_DIR = ../../toolchain

LIB_DIR = ../../lib

SRC = uart_example.c

OBJ_DUMP = 1 # Uncomment if disassembly is needed

# CFLAGS = # Use as needed

# OPTIMIZATION = -02 # Default is -O0


include $(TOOLCHAIN_DIR)/makefile

