module small_ntt
   #(   
        parameter N        = 64, // fixed for now
        parameter W        = 64, // word size, fixed for now
        parameter B        = 32, // bandwidth, must divide W
        parameter L        = 11, // BU latency
        parameter PRLLIN   = 0,  // first stage parallel to input
        parameter PRLLOUT  = 0   // last stage parallel to output
    )
    (
        input              clk,
        input              rst,
        input      [2  :0] cmd,
        input      [1  :0] mode,
        input      [B-1:0] i_data,
        input              i_valid,
        output reg [B-1:0] o_data,
        output reg         o_valid,
        output reg         busy
    );

`include "small_ntt_cmd.vh"

localparam LOGN    = $clog2(N);
localparam LOGLOGN = $clog2(LOGN); 
localparam LOGWB   = $clog2(W/B);
localparam WBMASK  = (1 << LOGWB) - 1;
localparam P       = (B >= W)? (W*N)/B - (N/2) : N/2; // after P clock cycles, processing is started, if PRLLIN is enabled. todo: adapt for GS

// states, todo: add glitch protection as HW codes
localparam ST_IDLE     = 4'd0;
localparam ST_Q        = 4'd1;
localparam ST_TWIDDLE  = 4'd2;
localparam ST_POLY_IN  = 4'd3;
localparam ST_NTT0     = 4'd4;
localparam ST_NTT1     = 4'd5;
localparam ST_POLY_OUT = 4'd6;
localparam ST_TWM0     = 4'd7;
localparam ST_TWM1     = 4'd8;

// data registers
reg [W-1:0] poly [0:N-1];
reg [W-1:0] psi  [0:N-1];
reg [W-1:0] q;

// control registers
reg  [3:0]   state;
reg  [LOGN+LOGWB-1:0] ctr0; // general purpose counter 0, todo: update the width w.r.t. B
reg  [LOGN+LOGWB-1:0] ctr1; // general purpose counter 1
reg  [LOGLOGN   -1:0] ctrS; // stage counter
wire [LOGN      -1:0] maskS; // stage mask

// control signals generated by FSM
reg [3:0] next_state;
reg ctr0_inc, ctr0_rst;
reg ctrS_inc, ctrS_rst;
reg ctr1_inc, ctr1_rst;
reg wpoly, upoly_ntt, upoly_mul, wpsi, wq;

// mode register
reg [1:0] mode_q;
reg mode_set;

// buttefly inputs
wire [LOGN-1:0] poly_ida;
wire [LOGN-1:0] poly_idb;
wire [LOGN-1:0] psi_idx;

wire [W-   1:0] A_i;
wire [W-   1:0] B_i;
wire [W-   1:0] psi_i;
wire [W-   1:0] A_o;
wire [W-   1:0] B_o;
wire [W-   1:0] M_o;

reg  sr_i;
wire sr_o;


///////////////////// BU address generation /////////////////////////////

assign maskS    = (1 << ctrS) - 1; // can be computed sequentially
assign poly_ida = ctr0;
assign poly_idb = (mode_q == 0) ? ctr0 : ctr0 + (N/2);
assign psi_idx  = (mode_q == 0) ? ctr0 : maskS + (ctr0 & maskS);
assign A_i      = poly[poly_ida];
assign B_i      = poly[poly_idb];
assign psi_i    = psi[psi_idx];

/////////////////////////////////////////////////////////////////////////


for(genvar i = 0; i < N ;i = i + 1) begin: TWIDDLE_LOAD_GEN
    for(genvar j = 0; j < (W/B); j = j + 1) begin
        always @(posedge clk) begin
            if (rst) // todo add reset
                psi[i][j*B +: B] <= 0;
            else if (wpsi && ctr0 == (i*(W/B) + j))
                psi[i][j*B +: B] <= i_data;
        end
    end
end


for(genvar i = 0; i < N ;i = i + 1) begin: POLY_GEN
    for(genvar j = 0; j < (W/B); j = j + 1) begin
        always @(posedge clk) begin
            if (rst)
                poly[i][j*B +: B] <= 0;
            else if (upoly_mul && (ctr1 == i))
                poly[i][j*B +: B] <= M_o >> (j*B);
            else if (upoly_ntt && ((ctr1 << 1) == i))
                poly[i][j*B +: B] <= A_o >> (j*B);
            else if (upoly_ntt && (((ctr1 << 1) + 1) == i))
                poly[i][j*B +: B] <= B_o >> (j*B);
            else if (wpoly && ctr1 == (i*(W/B) + j))
                poly[i][j*B +: B] <= i_data;
        end
    end
end


for(genvar j = 0; j < (W/B); j = j + 1) begin
    always @(posedge clk) begin
        if (rst)
            q[j*B +: B] <= 0;
        else if (wq && ctr0 == j)
            q[j*B +: B] <= i_data;
    end
end


always @(posedge clk) begin
    if (rst)
        ctr0 <= 0;
    else if (ctr0_inc)
        ctr0 <= ctr0 + 1;
    else if (ctr0_rst)
        ctr0 <= 0;
end

always @(posedge clk) begin
    if (rst)
        ctrS <= 0;
    else if (ctrS_inc)
        ctrS <= ctrS + 1;
    else if (ctrS_rst)
        ctrS <= 0;
end

always @(posedge clk) begin
    if (rst)
        ctr1 <= 0;
    else if (ctr1_inc)
        ctr1 <= ctr1 + 1;
    else if (ctr1_rst)
        ctr1 <= 0;
end


always @(posedge clk) begin
    if (rst)
        state <= ST_IDLE;
    else
        state <= next_state;
end


always @(posedge clk) begin
    if (rst)
        mode_q <= 0;
    else if (mode_set)
        mode_q <= mode;
end


butterfly btfu
    (
        .clk(clk),
        .rst(rst),
        .CT(1),
        .MT(0),
        .A(A_i),
        .B(B_i),
        .PSI(psi_i),
        .q(q),
        .E(A_o),
        .O(B_o),
        .MUL(M_o)
    );


shiftreg #(.SHIFT(L), .DATA(1)) shreg
    (
        .clk(clk),
        .reset(rst),
        .data_in(sr_i),
        .data_out(sr_o)
    );


always @(*) begin

    next_state = state;
    ctr0_inc = 0;
    ctr0_rst = 0;
    ctr1_inc = 0;
    ctr1_rst = 0;
    ctrS_inc = 0;
    ctrS_rst = 0;
    wpoly = 0;
    upoly_ntt = 0;
    upoly_mul = 0;
    wpsi = 0;
    wq = 0;
    sr_i = 0;
    busy = 0;
    o_data = {B{1'b0}};
    o_valid = 0;
    mode_set = 0;


    case (state)
        ST_IDLE: begin

            if (cmd == `CMD_LOAD_Q) begin
                next_state = ST_Q;
                if (i_valid) begin
                    ctr0_inc = 1;
                    wq = 1;
                end
            end
            if (cmd == `CMD_LOAD_TWIDDLE) begin
                next_state = ST_TWIDDLE;
                if (i_valid) begin
                    ctr0_inc = 1;
                    wpsi = 1;
                end
            end
            else if (cmd == `CMD_LOAD_POLY) begin
                next_state = ST_POLY_IN;
                mode_set = 1;
                if (i_valid) begin
                    ctr1_inc = 1;
                    wpoly = 1;
                end
            end
            else if (cmd == `CMD_RST)
                next_state = ST_IDLE;

        end
        ST_Q: begin

            if (i_valid) begin
                wq = 1;
                if (ctr0 == ((W/B) - 1)) begin
                    next_state = ST_IDLE;
                    ctr0_rst = 1;
                end
                else
                    ctr0_inc = 1;
            end

        end
        ST_TWIDDLE: begin

            if (i_valid) begin
                wpsi = 1;
                if (ctr0 == (N * (W/B) - 1)) begin
                    next_state = ST_IDLE;
                    ctr0_rst = 1;
                end
                else
                    ctr0_inc = 1;
            end

        end
        ST_POLY_IN: begin

            if (i_valid) begin
                wpoly = 1;
                if (PRLLIN && (ctr1 == P)) begin
                    next_state = (mode_q == 0) ? ST_NTT0 : ST_TWM0;
                    ctr1_inc = 1;
                end
                else if (ctr1 == (N * (W/B) - 1)) begin
                    next_state = (mode_q == 0) ? ST_NTT0 : ST_TWM0;
                    ctr1_rst = 1;
                end
                else
                    ctr1_inc = 1;
            end

        end
        ST_TWM0: begin

            busy = 1;
            sr_i = 1;
            if (ctr0 == (N - 1)) begin
                ctr0_rst = 1;
                next_state = ST_TWM1;
            end
            else
                ctr0_inc = 1;

            // write bu output to poly reg
            if (sr_o) begin
                ctr1_inc = 1;
                upoly_mul = 1;
            end
            else begin
                ctr1_rst = 1; // now it works since ctr1_inc has priority over ctr1_rst
            end

        end
        ST_TWM1: begin

            busy = 1;
            // BU input for next stage is valid after processing half of the poly
            if ((ctr1 == (N - 1))) begin
                ctr1_rst = 1;
                next_state = ST_POLY_OUT;
                ctrS_rst = 1;
            end

            // write BU output to poly reg
            if (sr_o) begin
                ctr1_inc = 1;
                upoly_mul = 1;
            end
            else begin
                ctr1_rst = 1;
            end

        end
        ST_NTT0: begin

            // keep getting input if parallelism enabled between poly read and stage 1
            if (PRLLIN && ctrS == 0) begin // only in the first stage
                if (i_valid) begin
                    wpoly = 1;
                    if (ctr1 == (N * (W/B) - 1)) begin
                        ctr1_rst = 1;
                    end
                    else
                        ctr1_inc = 1;
                end
            end

            busy = 1;
            sr_i = 1;
            if (ctr0 == ((N/2) - 1)) begin
                ctr0_rst = 1;
                next_state = ST_NTT1;
            end
            else
                ctr0_inc = 1;

            // write bu output to poly reg
            if (sr_o) begin
                ctr1_inc = 1;
                upoly_ntt = 1;
            end
            else begin
                ctr1_rst = 1; // now it works since ctr1_inc has priority over ctr1_rst
            end

        end
        ST_NTT1: begin

            busy = 1;
            // BU input for next stage is valid after processing half of the poly
            if ((ctr1 == (N/4)) && (ctrS != (LOGN - 1))) begin
                next_state = ST_NTT0;
                ctrS_inc = 1; // go to next stage
            end
            else if (!PRLLOUT && (ctr1 == ((N/2) - 1))) begin
                ctr1_rst = 1;
                next_state = ST_POLY_OUT;
                ctrS_rst = 1;
            end

            // write BU output to poly reg
            if (sr_o) begin
                ctr1_inc = 1;
                upoly_ntt = 1;
                if (PRLLOUT && (ctrS == (LOGN - 1))) begin // assume W*2 >= B go to output state
                    next_state = ST_POLY_OUT;
                    ctrS_rst = 1;
                end
            end
            else begin
                ctr1_rst = 1;
            end

        end
        ST_POLY_OUT: begin

            o_valid = 1;
            o_data = poly[ctr0 >> LOGWB][(ctr0 & WBMASK) * B +: B];
            busy = 1;
            if (ctr0 == ((N * (W/B)) - 1)) begin
                next_state = ST_IDLE;
                ctr0_rst = 1;
            end
            else if(cmd == 5)
                ctr0_inc = 1;

            if (PRLLOUT) begin
                // write BU output to poly reg
                if (sr_o) begin
                    ctr1_inc = 1;
                    upoly_ntt = 1;
                end
                else begin
                    ctr1_rst = 1;
                end
            end

        end



    endcase

end




endmodule