#include <stdint.h>
#include <string.h>
#include <stdbool.h>
#include "inner.h"

#include "util.h"
#include "symmetric.h"
#include "keccak.h"
#include "keccak_tests.h"
#include "falcon.h"

/* Include the vectors generated by extract_vectors.c */
#include "extracted_vectors.h"
/* Include legacy vectors if needed, otherwise this can be commented out */
#include "falcon_testvectors.h"

/* ================================================================== */
/* CONSTANTS & MACROS                                                 */
/* ================================================================== */

/* If FALCON_ERR_* constants are missing, define them here: */
#ifndef FALCON_ERR_FORMAT
#define FALCON_ERR_RANDOM     -1
#define FALCON_ERR_SIZE       -2
#define FALCON_ERR_FORMAT     -3
#define FALCON_ERR_BADSIG     -4
#define FALCON_ERR_BADARG     -5
#endif

#define FALCON_SIG_COMPRESSED   1
#define FALCON_SIG_PADDED       2
#define FALCON_SIG_CT           3

/* Falcon-512 parameters */
#define LOGN                    9
#define N                       (1 << LOGN)

/* General purpose large buffer for tests (72KB to be safe for all operations) */
#define WORK_BUFFER_SIZE (72 * 1024)

/* Allocate actual memory for operations */
static uint8_t pool_buffer[WORK_BUFFER_SIZE];

/* Pointers used by tests */
uint8_t *tmpvv;
size_t tmpvv_len;

void test_falcon_verify() {
    int result;
    
    print_string("\n=== Falcon-512 Verification NEW ===\n");

    /* ----------------------------------------------------------------
     * TEST 1: COMPRESSED SIGNATURE
     * ---------------------------------------------------------------- */
    print_string("[TEST] Verify COMPRESSED... ");
    
    result = falcon_verify(test_sig_compressed, test_sig_compressed_len, FALCON_SIG_COMPRESSED,
                           test_pubkey, sizeof(test_pubkey),
                           test_message, test_message_len,
                           tmpvv, tmpvv_len);

    if (result == 0) {
        print_string("PASS COMPRESSED SIGNATURE");
        print_string("\nSignature Size: ");
        print_dec((uint32_t)test_sig_compressed_len);
        print_string(" bytes\n");
    } else {
        print_string("FAIL (Error: ");
        print_u32((uint32_t)result);
        print_string(")\n");
    }

    /* ----------------------------------------------------------------
     * TEST 2: PADDED SIGNATURE
     * ---------------------------------------------------------------- */
    print_string("[TEST] Verify PADDED...     ");

    result = falcon_verify(test_sig_padded, test_sig_padded_len, FALCON_SIG_PADDED,
                           test_pubkey, sizeof(test_pubkey),
                           test_message, test_message_len,
                           tmpvv, tmpvv_len);

    if (result == 0) {
        print_string("PASS PADDED SIGNATURE");
        print_string("\nSignature Size: ");
        print_dec((uint32_t)test_sig_padded_len);
        print_string(" bytes\n");
    } else {
        print_string("FAIL (Error: ");
        print_u32((uint32_t)result);
        print_string(")\n");
    }

    /* ----------------------------------------------------------------
     * TEST 3: CT (CONSTANT-TIME) SIGNATURE
     * ---------------------------------------------------------------- */
    print_string("[TEST] Verify CT...         ");

    result = falcon_verify(test_sig_ct, test_sig_ct_len, FALCON_SIG_CT,
                           test_pubkey, sizeof(test_pubkey),
                           test_message, test_message_len,
                           tmpvv, tmpvv_len);

    if (result == 0) {
        print_string("PASS CT SIGNATURE");
        print_string("\nSignature Size: ");
        print_dec((uint32_t)test_sig_ct_len);
        print_string(" bytes\n");
    } else if (result == FALCON_ERR_SIZE) {
        print_string("FAIL (FALCON_ERR_SIZE)\n");
    } else if (result == FALCON_ERR_FORMAT) {
        print_string("FAIL (FALCON_ERR_FORMAT)\n");
    } else if (result == FALCON_ERR_BADSIG) {
        print_string("FAIL (FALCON_ERR_BADSIG)\n");
    } else {
        print_string("FAIL (Error: ");
        print_u32((uint32_t)result);
        print_string(")\n");
    }
    
    print_string("\n=== Falcon-512 Verification END===\n");
}


int main() {
    tmpvv = pool_buffer;
    tmpvv_len = WORK_BUFFER_SIZE;
    
    //these tests worked well for falcon API
    /*test_keccak_simple();
    test_keccak_golden();
    test_falcon_api();*/
    
    test_falcon_verify();
    
    return 0;
}