#include <stdint.h>
#include <string.h>
#include <stdbool.h>
#include "inner.h"
#include "uart.h"
#include "util.h"
#include "symmetric.h"
#include "keccak.h"

/* Include the vectors generated by extract_vectors.c */
#include "extracted_vectors.h"
/* Include legacy vectors if needed, otherwise this can be commented out */
#include "falcon_testvectors.h"

/* ================================================================== */
/* CONSTANTS & MACROS                                                 */
/* ================================================================== */

/* If FALCON_ERR_* constants are missing, define them here: */
#ifndef FALCON_ERR_FORMAT
#define FALCON_ERR_RANDOM     -1
#define FALCON_ERR_SIZE       -2
#define FALCON_ERR_FORMAT     -3
#define FALCON_ERR_BADSIG     -4
#define FALCON_ERR_BADARG     -5
#endif

#define FALCON_SIG_COMPRESSED   1
#define FALCON_SIG_PADDED       2
#define FALCON_SIG_CT           3

/* Falcon-512 parameters */
#define LOGN                    9
#define N                       (1 << LOGN)

/* Temporary buffer size for verification */
#define FALCON_TMPSIZE_VERIFY(LOGN) ((8u << (LOGN)) + 1)

/* General purpose large buffer for tests (72KB to be safe for all operations) */
#define WORK_BUFFER_SIZE (72 * 1024)

/* ================================================================== */
/* TYPEDEFS & GLOBAL DATA                                             */
/* ================================================================== */

#ifndef FALCON_H__
typedef struct { uint64_t opaque[64]; } shake256_context;
#endif

/* Allocate actual memory for operations */
static uint8_t pool_buffer[WORK_BUFFER_SIZE];

/* Pointers used by tests */
uint8_t *tmpvv;
size_t tmpvv_len;

/* ================================================================== */
/* PROTOTYPES                                                         */
/* ================================================================== */
// #include "keccak.h"
/* SHAKE256 API */
void shake256_init(shake256_context *sc);
void shake256_inject(shake256_context *sc, const void *data, size_t len);
void shake256_flip(shake256_context *sc);
void shake256_extract(shake256_context *sc, void *out, size_t len);
int shake256_init_prng_from_seed(shake256_context *sc, const void *seed, size_t seed_len);

/* Falcon API */
int falcon_verify(const void *sig, size_t sig_len, int sig_type,
                  const void *pubkey, size_t pubkey_len,
                  const void *data, size_t data_len,
                  void *tmp, size_t tmp_len);

/* ================================================================== */
/* TEST FUNCTIONS                                                     */
/* ================================================================== */

void test_falcon_verify_only_new() {
    int result;
    
    print_string("\n=== Falcon-512 Verification NEW ===\n");

    /* ----------------------------------------------------------------
     * TEST 1: COMPRESSED SIGNATURE
     * ---------------------------------------------------------------- */
    print_string("[TEST] Verify COMPRESSED... ");
    
    result = falcon_verify(test_sig_compressed, test_sig_compressed_len, FALCON_SIG_COMPRESSED,
                           test_pubkey, sizeof(test_pubkey),
                           test_message, test_message_len,
                           tmpvv, tmpvv_len);

    if (result == 0) {
        print_string("PASS (Size: ");
        print_u32((uint32_t)test_sig_compressed_len);
        print_string(" bytes)\n");
    } else {
        print_string("FAIL (Error: ");
        print_u32((uint32_t)result);
        print_string(")\n");
    }

    /* ----------------------------------------------------------------
     * TEST 2: PADDED SIGNATURE
     * ---------------------------------------------------------------- */
    print_string("[TEST] Verify PADDED...     ");

    result = falcon_verify(test_sig_padded, test_sig_padded_len, FALCON_SIG_PADDED,
                           test_pubkey, sizeof(test_pubkey),
                           test_message, test_message_len,
                           tmpvv, tmpvv_len);

    if (result == 0) {
        print_string("PASS (Size: ");
        print_u32((uint32_t)test_sig_padded_len);
        print_string(" bytes)\n");
    } else {
        print_string("FAIL (Error: ");
        print_u32((uint32_t)result);
        print_string(")\n");
    }

    /* ----------------------------------------------------------------
     * TEST 3: CT (CONSTANT-TIME) SIGNATURE
     * ---------------------------------------------------------------- */
    print_string("[TEST] Verify CT...         ");

    result = falcon_verify(test_sig_ct, test_sig_ct_len, FALCON_SIG_CT,
                           test_pubkey, sizeof(test_pubkey),
                           test_message, test_message_len,
                           tmpvv, tmpvv_len);

    if (result == 0) {
        print_string("PASS (Size: ");
        print_u32((uint32_t)test_sig_ct_len);
        print_string(" bytes)\n");
    } else if (result == FALCON_ERR_SIZE) {
        print_string("FAIL (FALCON_ERR_SIZE)\n");
    } else if (result == FALCON_ERR_FORMAT) {
        print_string("FAIL (FALCON_ERR_FORMAT)\n");
    } else if (result == FALCON_ERR_BADSIG) {
        print_string("FAIL (FALCON_ERR_BADSIG)\n");
    } else {
        print_string("FAIL (Error: ");
        print_u32((uint32_t)result);
        print_string(")\n");
    }
    
    print_string("\n=== Falcon-512 Verification NEW  END===\n");
}

void test_keccak_simple() {
    shake256_context sc;
    uint8_t out[16];
    
    print_string("\n--- Keccak Check ---\n");
    
    memset(&sc, 0, sizeof(sc));
    
    shake256_init_prng_from_seed(&sc, "abcd", 4);
    
    shake256_extract(&sc, out, 16);
    
    uint32_t val = (out[0] << 24) | (out[1] << 16) | (out[2] << 8) | out[3];
    
    print_string("First 4 bytes (Expect 0x16c60651): 0x");
    print_u32(val); 
    print_string("\n");
}

/* ================================================================== */
/* TEST FUNCTION                                                      */
/* ===/* ================================================================== */
/* EXPECTED GOLDEN OUTPUTS (Standard SHAKE256)                        */
/* ================================================================== */

/* SHAKE256("abc", 32) -> 48336660... */
static const uint8_t golden_abcdefgh_dil[32] = {
    0x3a,0x3b,0x28,0xb6,0x96,0x22,0xde,0x01,0x55,
    0xfd,0xd9,0xdf,0xbd,0x6f,0xcb,0xca,0xfc,0x87,
    0x87,0x45,0xe9,0xe5,0x5c,0x3d,0x27,0x36,0xc0,
    0xc9,0xf5,0x08,0x23,0xc1
};

/* SHAKE256("abcd", 32) -> 16c60651... */
static const uint8_t golden_abcd_dil[32] = {
    0x16, 0xc6, 0x06 ,0x51 ,0xe6 ,0x44 ,0x8e ,0xb9 
    ,0xc1 ,0x77 ,0x23 ,0x4f ,0xdd ,0x73 ,0xce ,0x60 
    ,0xcb ,0xfe ,0x6d ,0x80 ,0x5c ,0x0e ,0x8f ,0x4c 
    ,0x95 ,0x69 ,0x86 ,0x37 ,0x6b ,0xe2 ,0x86 ,0xd6
};

void test_keccak_golden() {
    shake256_context sc;
    uint8_t out[32];
    int i;
    
    print_string("\n=== Keccak FULL DEBUG Check ===\n");

    /* TEST 1: "abcd" (4 bytes) */
    print_string("\n[TEST] 'abcd' (4 bytes)\n");
    shake256_init(&sc);
    shake256_inject(&sc, "abcd", 4);
    shake256_flip(&sc);
    shake256_extract(&sc, out, 32);
    
    print_string(" Expect: ");
    print_hex(golden_abcd_dil, 32, 0);
    print_string(" Got:    ");
    print_hex(out, 32, 0);

    if (memcmp(out, golden_abcd_dil, 32) == 0) print_string(" RESULT: PASS\n");
    else print_string(" RESULT: FAIL\n");

    /* TEST 2: "abcd" (4 bytes) */
    print_string("\n[TEST] 'abcdefgh' (8 bytes)\n");
    shake256_init(&sc);
    shake256_inject(&sc, "abcdefgh", 8);
    shake256_flip(&sc);
    shake256_extract(&sc, out, 32);
    
    print_string(" Expect: ");
    print_hex(golden_abcdefgh_dil, 32, 0);
    print_string(" Got:    ");
    print_hex(out, 32, 0);

    if (memcmp(out, golden_abcdefgh_dil, 32) == 0) print_string(" RESULT: PASS\n");
    else print_string(" RESULT: FAIL\n");

    
    print_string("==================================\n");
}




/* ================================================================== */
/* TEST FUNCTION                                                      */
/* ================================================================== */

void test_dilithium_api() {
    uint8_t out[32];

    print_string("\n=== Test via Symmetric.h API (Dilithium) ===\n");

    /* ----------------------------------------------------------------
     * TEST 1: "abcd" (4 bytes)
     * ---------------------------------------------------------------- */
    print_string("\n[TEST] dilithium_shake256('abcd')...\n");
    
    dilithium_shake256(out, 32, (const uint8_t*)"abcd", 4);
    
    print_string(" Expect: ");
    print_hex(golden_abcd_dil, 32, 0);
    print_string(" Got:    ");
    print_hex(out, 32, 0);

    if (memcmp(out, golden_abcd_dil, 32) == 0) {
        print_string(" RESULT: PASS\n");
    } else {
        print_string(" RESULT: FAIL\n");
    }

    /* ----------------------------------------------------------------
     * TEST 2: "abc" (3 bytes)
     * Unaligned. Dilithium typically ignores partial words (3 >> 2 = 0).
     * This confirms if Dilithium API fails for unaligned data.
     * ---------------------------------------------------------------- */
    print_string("\n[TEST] dilithium_shake256('abcdefgh')....\n");
    
    dilithium_shake256(out, 32, (const uint8_t*)"abcdefgh", 8);
    
    print_string(" Expect: ");
    print_hex(golden_abcdefgh_dil, 32, 0);
    print_string(" Got:    ");
    print_hex(out, 32, 0);

    if (memcmp(out, golden_abcdefgh_dil, 32) == 0) {
        print_string(" RESULT: PASS\n");
    } else {
        print_string(" RESULT: FAIL (Expected behavior for Dilithium unaligned)\n");
    }
}

void test_unaligned_injection() {
    shake256_context sc;
    uint8_t out[32];
    /* "12345" aligned */
    uint8_t buffer_aligned[] = "12345678"; 
    /* "12345" unaligned (offset by 1) */
    uint8_t *buffer_unaligned = buffer_aligned + 1; 

    print_string("\n=== Test: Unaligned Injection ===\n");

    /* 1. Reference: Hash "2345" (aligned logic) */
    shake256_init(&sc);
    shake256_inject(&sc, "2345", 4);
    shake256_flip(&sc);
    shake256_extract(&sc, out, 32);
    uint32_t ref_hash = (out[0]<<24)|(out[1]<<16)|(out[2]<<8)|out[3];
    print_string("Reference Hash ('2345'): "); print_u32(ref_hash); print_string("\n");

    /* 2. Test: Hash "2345" (unaligned pointer) */
    shake256_init(&sc);
    /* buffer_unaligned points to '2', but address is Odd */
    shake256_inject(&sc, buffer_unaligned, 4); 
    shake256_flip(&sc);
    shake256_extract(&sc, out, 32);
    uint32_t test_hash = (out[0]<<24)|(out[1]<<16)|(out[2]<<8)|out[3];
    print_string("Unaligned Hash ('2345'): "); print_u32(test_hash); print_string("\n");

    if (ref_hash == test_hash) {
        print_string("RESULT: PASS (Wrapper handles unaligned safe)\n");
    } else {
        print_string("RESULT: FAIL (DMA/Race condition detected)\n");
    }
}


/* * Golden Output for SHAKE256("abc") - Length 160 bytes 
 * Generated via Standard Keccak Tools
 */
static const uint8_t golden_long_squeeze[160] = {
    0x48, 0x33, 0x66, 0x60, 0x13, 0x60, 0xa8, 0x77, 0x1c, 0x68, 0x63, 0x08, 0x0c, 0xc4, 0x11, 0x4d,
    0x8d, 0xb4, 0x45, 0x30, 0xf8, 0xf1, 0xe1, 0xee, 0x4f, 0x94, 0xea, 0x37, 0xe7, 0x8b, 0x57, 0x39,
    0xa8, 0x7d, 0x6b, 0xef, 0x16, 0x9f, 0x68, 0x47, 0x50, 0x1d, 0x0c, 0xf6, 0xe0, 0x80, 0x11, 0x1f,
    0x4e, 0x17, 0x22, 0x0e, 0x22, 0xea, 0x14, 0x29, 0x7f, 0x24, 0x2b, 0xc9, 0xc5, 0x93, 0x21, 0x39,
    0x57, 0x15, 0x52, 0x56, 0xb6, 0x3d, 0xee, 0xf7, 0x2f, 0x93, 0x0f, 0x47, 0x31, 0x64, 0x42, 0x3b,
    0x92, 0x44, 0x2c, 0xe0, 0x79, 0x6f, 0xa9, 0xe5, 0x81, 0x44, 0xf7, 0xec, 0x42, 0x7e, 0x64, 0xf5,
    0x63, 0x50, 0xad, 0xc2, 0x97, 0x51, 0x1d, 0x2b, 0x5a, 0x72, 0x44, 0x82, 0x20, 0x24, 0x88, 0x8c,
    0x5b, 0x74, 0x26, 0x49, 0x6e, 0x47, 0x6e, 0x43, 0xf4, 0xc8, 0x25, 0x64, 0x37, 0xcf, 0x7e, 0x08,
    /* -- Boundary of 1st Block (136 bytes) is here -- */
    0x19, 0x50, 0x0c, 0x6c, 0x61, 0x69, 0x86, 0x55, /* Indices 128-135 */
    0x08, 0x69, 0x23, 0x96, 0x19, 0x6f, 0x1d, 0x9a, /* Indices 136-143 (Danger Zone) */
    0x2c, 0x37, 0x7b, 0x21, 0x52, 0x09, 0x2a, 0xd9, 
    0x2f, 0x04, 0x60, 0xd0, 0x4c, 0x11, 0x2b, 0x43  
};

void test_long_squeeze() {
    shake256_context sc;
    uint8_t out[160];
    int i;
    int mismatches = 0;

    print_string("\n=== Test: Long Squeeze (160 Bytes) ===\n");
    print_string("Checking for boundaries at 128 or 136 bytes...\n");

    shake256_init(&sc);
    shake256_inject(&sc, "abc", 3);
    shake256_flip(&sc);
    
    /* Request 160 bytes in one go */
    shake256_extract(&sc, out, 160);

    for (i = 0; i < 160; i++) {
        if (out[i] != golden_long_squeeze[i]) {
            if (mismatches == 0) {
                /* Print the first failure only */
                print_string("FAIL at Index: ");
                print_u32(i);
                print_string("\n");
                print_string("  Expected: "); print_u32(golden_long_squeeze[i]);
                print_string("\n  Got:      "); print_u32(out[i]);
                print_string("\n");
            }
            mismatches++;
        }
    }

    if (mismatches == 0) {
        print_string("RESULT: PASS (Long squeeze safe)\n");
    } else {
        print_string("RESULT: FAIL (Total mismatches: ");
        print_u32(mismatches);
        print_string(")\n");
    }
}

void debug_squeeze_words() {
    shake256_context sc;
    uint32_t word;
    int i;
    
    /* Expected first 9 words for "abc" */
    uint32_t expected[] = {
        0x60663348, // Word 0
        0x77a86013, // Word 1
        0x0863681c, // Word 2
        0x4d11c40c, // Word 3
        0x3045b48d, // Word 4
        0xeee1f1f8, // Word 5
        0x37ea944f, // Word 6
        0x39578be7, // Word 7 (Last of 32-byte block)
        0xef6b7da8  // Word 8 (First of NEXT block - THE FAIL POINT)
    };

    print_string("\n=== Squeeze Micro-Debug ===\n");
    
    shake256_init(&sc);
    shake256_inject(&sc, "abc", 3);
    shake256_flip(&sc);
    
    for(i=0; i<9; i++) {
        keccak_squeeze(&word, NULL, 1); // Ask for 1 word at a time
        
        print_string("Word "); print_u32(i); 
        print_string(": Got "); print_u32(word);
        
        if (word == expected[i]) {
            print_string(" [OK]\n");
        } else {
            print_string(" [FAIL] Exp "); print_u32(expected[i]); print_string("\n");
        }
    }
}
void debug_squeeze_repeat() {
    shake256_context sc;
    uint32_t buf1[8];
    uint32_t buf2[8];
    int i;
    
    print_string("\n=== Debug: Squeeze Repeat Analysis ===\n");
    
    shake256_init(&sc);
    shake256_inject(&sc, "abc", 3);
    shake256_flip(&sc);
    
    /* Request first 32 bytes */
    keccak_squeeze(buf1, NULL, 8);
    
    /* Request next 32 bytes (supposedly) */
    keccak_squeeze(buf2, NULL, 8);
    
    print_string("Chunk 1 (Words 0-3): ");
    print_u32(buf1[0]); print_string(" "); print_u32(buf1[1]); print_string(" ");
    print_u32(buf1[2]); print_string(" "); print_u32(buf1[3]); print_string("\n");

    print_string("Chunk 2 (Words 0-3): ");
    print_u32(buf2[0]); print_string(" "); print_u32(buf2[1]); print_string(" ");
    print_u32(buf2[2]); print_string(" "); print_u32(buf2[3]); print_string("\n");

    if (buf1[0] == buf2[0] && buf1[1] == buf2[1]) {
        print_string("CONCLUSION: Hardware resets index to 0 every call!\n");
        print_string("Status: We are reading the same 32 bytes over and over.\n");
    } else {
        print_string("CONCLUSION: Hardware returns different data (Garbage or Next).\n");
    }
}
int main() {
    tmpvv = pool_buffer;
    tmpvv_len = WORK_BUFFER_SIZE;

    print_string("\n=== Falcon-512 Function Tests ===\n");
    
    test_keccak_simple();
    test_keccak_golden();
    test_dilithium_api();
    //test_unaligned_injection();
    //test_long_squeeze();
    debug_squeeze_words();
    debug_squeeze_repeat();
    test_falcon_verify_only_new();
    
    return 0;
}