#include <stdint.h>
#include <string.h>
#include <stdbool.h>
#include "inner.h"
#include "uart.h"
#include "util.h"

/* Include the vectors generated by extract_vectors.c */
#include "extracted_vectors.h"
/* Include legacy vectors if needed, otherwise this can be commented out */
#include "falcon_testvectors.h"

/* ================================================================== */
/* CONSTANTS & MACROS                                                 */
/* ================================================================== */

/* If FALCON_ERR_* constants are missing, define them here: */
#ifndef FALCON_ERR_FORMAT
#define FALCON_ERR_RANDOM     -1
#define FALCON_ERR_SIZE       -2
#define FALCON_ERR_FORMAT     -3
#define FALCON_ERR_BADSIG     -4
#define FALCON_ERR_BADARG     -5
#endif

#define FALCON_SIG_COMPRESSED   1
#define FALCON_SIG_PADDED       2
#define FALCON_SIG_CT           3

/* Falcon-512 parameters */
#define LOGN                    9
#define N                       (1 << LOGN)

/* Temporary buffer size for verification */
#define FALCON_TMPSIZE_VERIFY(LOGN) ((8u << (LOGN)) + 1)

/* General purpose large buffer for tests (72KB to be safe for all operations) */
#define WORK_BUFFER_SIZE (72 * 1024)

/* ================================================================== */
/* TYPEDEFS & GLOBAL DATA                                             */
/* ================================================================== */

#ifndef FALCON_H__
typedef struct { uint64_t opaque[64]; } shake256_context;
#endif

/* Allocate actual memory for operations */
static uint8_t pool_buffer[WORK_BUFFER_SIZE];

/* Pointers used by tests */
uint8_t *tmpvv;
size_t tmpvv_len;

/* ================================================================== */
/* PROTOTYPES                                                         */
/* ================================================================== */
// #include "keccak.h"
/* SHAKE256 API */
void shake256_init(shake256_context *sc);
void shake256_inject(shake256_context *sc, const void *data, size_t len);
void shake256_flip(shake256_context *sc);
void shake256_extract(shake256_context *sc, void *out, size_t len);
int shake256_init_prng_from_seed(shake256_context *sc, const void *seed, size_t seed_len);

/* Falcon API */
int falcon_verify(const void *sig, size_t sig_len, int sig_type,
                  const void *pubkey, size_t pubkey_len,
                  const void *data, size_t data_len,
                  void *tmp, size_t tmp_len);

/* ================================================================== */
/* TEST FUNCTIONS                                                     */
/* ================================================================== */

void test_falcon_verify_only_new() {
    int result;
    
    print_string("\n=== Falcon-512 Verification NEW ===\n");

    /* ----------------------------------------------------------------
     * TEST 1: COMPRESSED SIGNATURE
     * ---------------------------------------------------------------- */
    print_string("[TEST] Verify COMPRESSED... ");
    
    result = falcon_verify(test_sig_compressed, test_sig_compressed_len, FALCON_SIG_COMPRESSED,
                           test_pubkey, sizeof(test_pubkey),
                           test_message, test_message_len,
                           tmpvv, tmpvv_len);

    if (result == 0) {
        print_string("PASS (Size: ");
        print_u32((uint32_t)test_sig_compressed_len);
        print_string(" bytes)\n");
    } else {
        print_string("FAIL (Error: ");
        print_u32((uint32_t)result);
        print_string(")\n");
    }

    /* ----------------------------------------------------------------
     * TEST 2: PADDED SIGNATURE
     * ---------------------------------------------------------------- */
    print_string("[TEST] Verify PADDED...     ");

    result = falcon_verify(test_sig_padded, test_sig_padded_len, FALCON_SIG_PADDED,
                           test_pubkey, sizeof(test_pubkey),
                           test_message, test_message_len,
                           tmpvv, tmpvv_len);

    if (result == 0) {
        print_string("PASS (Size: ");
        print_u32((uint32_t)test_sig_padded_len);
        print_string(" bytes)\n");
    } else {
        print_string("FAIL (Error: ");
        print_u32((uint32_t)result);
        print_string(")\n");
    }

    /* ----------------------------------------------------------------
     * TEST 3: CT (CONSTANT-TIME) SIGNATURE
     * ---------------------------------------------------------------- */
    print_string("[TEST] Verify CT...         ");

    result = falcon_verify(test_sig_ct, test_sig_ct_len, FALCON_SIG_CT,
                           test_pubkey, sizeof(test_pubkey),
                           test_message, test_message_len,
                           tmpvv, tmpvv_len);

    if (result == 0) {
        print_string("PASS (Size: ");
        print_u32((uint32_t)test_sig_ct_len);
        print_string(" bytes)\n");
    } else if (result == FALCON_ERR_SIZE) {
        print_string("FAIL (FALCON_ERR_SIZE)\n");
    } else if (result == FALCON_ERR_FORMAT) {
        print_string("FAIL (FALCON_ERR_FORMAT)\n");
    } else if (result == FALCON_ERR_BADSIG) {
        print_string("FAIL (FALCON_ERR_BADSIG)\n");
    } else {
        print_string("FAIL (Error: ");
        print_u32((uint32_t)result);
        print_string(")\n");
    }
    
    print_string("\n=== Falcon-512 Verification NEW  END===\n");
}

void test_keccak_simple() {
    shake256_context sc;
    uint8_t out[16];
    
    print_string("\n--- Keccak Check ---\n");
    
    memset(&sc, 0, sizeof(sc));
    
    shake256_init_prng_from_seed(&sc, "abcd", 4);
    
    shake256_extract(&sc, out, 16);
    
    uint32_t val = (out[0] << 24) | (out[1] << 16) | (out[2] << 8) | out[3];
    
    print_string("First 4 bytes (Expect 0x16c60651): 0x");
    print_u32(val); 
    print_string("\n");
}

/* ================================================================== */
/* MAIN                                                               */
/* ================================================================== */

int main() {
    /* Initialize memory pointers */
    tmpvv = pool_buffer;
    tmpvv_len = WORK_BUFFER_SIZE; // Use full size to be safe

    print_string("\n=== Falcon-512 Function Tests ===\n");
    
    /* 1. Check Hardware Accelerator (Keccak) */
    test_keccak_simple();
    
    /* 2. Run Verification Tests using extracted vectors */
    test_falcon_verify_only_new();
    
    return 0;
}