PROJ = gpio_example

TOOLCHAIN_DIR = ../../toolchain

LIB_DIR = ../../lib

SRC = gpio_example.c

OBJ_DUMP = 1 # Uncomment if disassembly is needed

# CFLAGS = # Use as needed

# OPTIMIZATION = -O2 # Default is -O0


include $(TOOLCHAIN_DIR)/makefile

